@default_files = ("biochip_arch_syn_final");

$pdf_mode = 1;

add_cus_dep('svg', 'pdf_tex', 0, 'inkscape' );
sub inkscape {
return system( "inkscape -D -z --file=\"$_[0].svg\" --export-pdf=\"$_[0].pdf\" --export-latex");
}
