cp $PWD/Fig/valve_mixer_storage_own_mixer.pdf cameraReady/Fig/
cp $PWD/Fig/valve_mixer_storage_own_mixer.pdf cameraReady/Fig/
cp $PWD/Fig/valve_mixer_storage_own_mixer.pdf cameraReady/Fig/
cp $PWD/Fig/valve_mixer_storage_own_mixer.pdf cameraReady/Fig/
cp $PWD/Fig/archi.pdf cameraReady/Fig/
cp $PWD/Fig/archi.pdf cameraReady/Fig/
cp $PWD/Fig/archi.pdf cameraReady/Fig/
cp $PWD/Fig/archi.pdf cameraReady/Fig/
cp $PWD/Fig/dynamic_devices.pdf cameraReady/Fig/
cp $PWD/Fig/dynamic_devices.pdf cameraReady/Fig/
cp $PWD/Fig/dynamic_devices.pdf cameraReady/Fig/
cp $PWD/Fig/dynamic_devices.pdf cameraReady/Fig/
cp $PWD/Fig/dynamic_devices.pdf cameraReady/Fig/
cp $PWD/Fig/dynamic_devices.pdf cameraReady/Fig/
cp $PWD/Fig/defects.pdf cameraReady/Fig/
cp $PWD/Fig/defects.pdf cameraReady/Fig/
cp $PWD/Fig/defects.pdf cameraReady/Fig/
cp $PWD/Fig/defects.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/ref_test_biochip.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/path_cutset.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/flow_path_model.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/minimum_loops.pdf cameraReady/Fig/
cp $PWD/Fig/cut_var.pdf cameraReady/Fig/
cp $PWD/Fig/cut_var.pdf cameraReady/Fig/
cp $PWD/Fig/cut_var.pdf cameraReady/Fig/
cp $PWD/Fig/cut_var.pdf cameraReady/Fig/
cp $PWD/Fig/cut_var.pdf cameraReady/Fig/
cp $PWD/Fig/cut_var.pdf cameraReady/Fig/
cp $PWD/Fig/control_test.pdf cameraReady/Fig/
cp $PWD/Fig/long_channel.pdf cameraReady/Fig/
cp $PWD/Fig/long_channel.pdf cameraReady/Fig/
cp $PWD/Fig/long_channel.pdf cameraReady/Fig/
cp $PWD/Fig/long_channel.pdf cameraReady/Fig/
cp $PWD/Fig/supper_cell.pdf cameraReady/Fig/
cp $PWD/Fig/supper_cell.pdf cameraReady/Fig/
cp $PWD/Fig/supper_cell.pdf cameraReady/Fig/
cp $PWD/Fig/supper_cell.pdf cameraReady/Fig/
cp $PWD/Fig/supper_cell.pdf cameraReady/Fig/
cp $PWD/Fig/supper_cell.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_test_example.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_test_example.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_test_example.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_test_example.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_test_example.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_test_example.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_test_example.pdf cameraReady/Fig/
cp $PWD/Fig/joint_loops.pdf cameraReady/Fig/
cp $PWD/Fig/joint_loops.pdf cameraReady/Fig/
cp $PWD/Fig/joint_loops.pdf cameraReady/Fig/
cp $PWD/Fig/joint_loops.pdf cameraReady/Fig/
cp $PWD/Fig/joint_loops.pdf cameraReady/Fig/
cp $PWD/Fig/joint_loops.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_cut_theorem.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_cut_theorem.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_cut_theorem.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_cut_theorem.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_cut_theorem.pdf cameraReady/Fig/
cp $PWD/Fig/multi_port_cut_theorem.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/trees_cuts_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/test_traditional.pdf cameraReady/Fig/
cp $PWD/Fig/kill_loops_example.pdf cameraReady/Fig/
cp $PWD/Fig/kill_loops_example.pdf cameraReady/Fig/
cp $PWD/Fig/kill_loops_example.pdf cameraReady/Fig/
