@default_files = ("j_fpva_test_final.tex");

$pdf_mode = 1;
$pdflatex = 'pdflatex --shell-escape -synctex=1 %O %S';

add_cus_dep('svg', 'pdf_tex', 0, 'inkscape' );
sub inkscape {
return system( "inkscape -D -z --file=\"$_[0].svg\" --export-pdf=\"$_[0].pdf\" --export-latex " ); 
}
