@default_files = ("dft_single_port_DAC18_final.tex");

$pdf_mode = 1;

add_cus_dep('svg', 'pdf_tex', 0, 'inkscape' );
sub inkscape {
return system( "inkscape -D -z --file=\"$_[0].svg\" --export-pdf=\"$_[0].pdf\" --export-latex && ./inkscape_fix \"$_[0]\" " ); 
}
